export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER';
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER';

export const ADD_LOADER_ITEM = 'ADD_LOADER_ITEM';
export const REMOVE_LOADER_ITEM = 'REMOVE_LOADER_ITEM';

export const SET_PROJECTS = 'SET_PROJECTS';

export const ADD_TASKS = 'ADD_TASKS';
